/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

/**
 *
 * @author HP
 */
public class Logo_Score extends javax.swing.JPanel {

    /**
     * Creates new form Logo_Score
     */
    public Logo_Score() {
        initComponents();
        this.setBounds(1000, 0, 196, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setBackground(java.awt.Color.lightGray);
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText(" Player :");
        add(jLabel1);
        jLabel1.setBounds(0, 350, 118, 32);

        jLabel4.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Level :");
        add(jLabel4);
        jLabel4.setBounds(10, 420, 94, 32);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/output-onlinepngtools (5).png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 4, 197, 260);

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText(" Score :");
        add(jLabel2);
        jLabel2.setBounds(0, 490, 108, 32);

        jTextField1.setOpaque(false);
        add(jTextField1);
        jTextField1.setBounds(120, 430, 70, 22);

        jTextField2.setOpaque(false);
        add(jTextField2);
        jTextField2.setBounds(120, 500, 70, 22);

        jLabel5.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Lives :");
        add(jLabel5);
        jLabel5.setBounds(10, 560, 96, 32);

        jTextField4.setOpaque(false);
        add(jTextField4);
        jTextField4.setBounds(120, 360, 70, 22);

        jTextField3.setOpaque(false);
        add(jTextField3);
        jTextField3.setBounds(120, 570, 70, 22);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
