/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.List;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

import static MainPackage.FinalArkanoidIsa.frame;

/**
 *
 * @author HP
 */
public class plan extends javax.swing.JPanel {

    /**
     * Creates new form plan
     */
    User u;
    
   public static ArrayList<User> UserList;

    public plan(String name) {
        u = null;
        UserList = new ArrayList<User>();
        initComponents();
        this.setBounds(0, 0, 1196, 1000);
        this.setVisible(true);
        boolean found = false;
        Load_Data.read();
        for (User user : UserList) {
            System.out.println(user.getName()+"         "+name);
            if (user.getName().equals(name)) {
                found = true;
                u = user;
                System.out.println(u.getName());
                break;
            }
        }
        if (found == false) {
            u = new User(name, 0, 1, 3);
            UserList.add(u);
        }
        if (u.getLevel() >= 1) {
            jButton4.setVisible(true);
        }
        if (u.getLevel() >= 2) {
            jButton1.setVisible(true);
        } else {
            jButton1.setVisible(false);
        }
        if (u.getLevel() >= 3) {
            jButton7.setVisible(true);
        } else {
            jButton7.setVisible(false);
        }
        if (u.getLevel() >= 4) {
            jButton5.setVisible(true);
        } else {
            jButton5.setVisible(false);
        }
        if (u.getLevel() >= 5) {
            jButton3.setVisible(true);
        } else {
            jButton3.setVisible(false);
        }

    }
    public  plan(User user){
    u = user;
     initComponents();
        this.setBounds(0, 0, 1196, 1000);
         if (u.getLevel() >= 1) {
            jButton4.setVisible(true);
        }
        if (u.getLevel() >= 2) {
            jButton1.setVisible(true);
        } else {
            jButton1.setVisible(false);
        }
        if (u.getLevel() >= 3) {
            jButton7.setVisible(true);
        } else {
            jButton7.setVisible(false);
        }
        if (u.getLevel() >= 4) {
            jButton5.setVisible(true);
        } else {
            jButton5.setVisible(false);
        }
        if (u.getLevel() >= 5) {
            jButton3.setVisible(true);
        } else {
            jButton3.setVisible(false);
        }
        for(User userr : UserList){
        if(user.getName()==userr.getName()){
        userr=user;
        Load_Data.save(UserList);
        }
        }
        this.setVisible(true);
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setLayout(null);

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton3.setText("Level 5");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(770, 110, 130, 60);

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(190, 750, 32, 8);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setText("Level 2");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(270, 520, 130, 31);

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton4.setText("Level 1");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(160, 790, 120, 31);

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton5.setText("level 4");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(620, 350, 110, 31);

        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton7.setText("Level 3");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(590, 630, 110, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/arkanoid-map.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -30, 1090, 1070);

        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton6.setText("Level 2");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(290, 490, 130, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /////toka
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //  JPanel p=new JPanel();
        //  p.setSize(WIDTH, WIDTH);
        // this.removeAll();
        /* FinalArkanoidIsa.frame.hide();
       FinalArkanoidIsa.frame= new JFrame("Bonus++;");
        FinalArkanoidIsa.frame.setSize(1196,1000);
        FinalArkanoidIsa.frame.setLocation(500, 0);
       // FinalArkanoidIsa.frame.add(new start());
      //FinalArkanoidIsa.frame.add(new Logo_Score());
      FinalArkanoidIsa.frame.add(new Level1());
      FinalArkanoidIsa. frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         FinalArkanoidIsa.frame.setVisible(true); 
         */
        frame.setVisible(false);
        // Frame_levels frame2=new Frame_levels();
        FinalArkanoidIsa.frame2 = new Frame_levels(u);
        FinalArkanoidIsa.frame2.setVisible(true);
        FinalArkanoidIsa.frame2.setFocusable(false);
        FinalArkanoidIsa.frame2.setSize(1200, 1000);
        FinalArkanoidIsa.frame2.add(new Level2(u));

    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
        // Frame_levels frame2=new Frame_levels();
        FinalArkanoidIsa.frame2 = new Frame_levels(u);
        FinalArkanoidIsa.frame2.setVisible(true);
        FinalArkanoidIsa.frame2.setFocusable(false);
        FinalArkanoidIsa.frame2.setSize(1200, 1000);
        FinalArkanoidIsa.frame2.add(new Level5(u));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
        // Frame_levels frame2=new Frame_levels();
        FinalArkanoidIsa.frame2 = new Frame_levels(u);
        FinalArkanoidIsa.frame2.setVisible(true);
        FinalArkanoidIsa.frame2.setFocusable(false);
        FinalArkanoidIsa.frame2.setSize(1200, 1000);
        FinalArkanoidIsa.frame2.add(new Level1(u));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
        //Frame_levels frame2=new Frame_levels();
        FinalArkanoidIsa.frame2 = new Frame_levels(u);
        FinalArkanoidIsa.frame2.setVisible(true);
        FinalArkanoidIsa.frame2.setFocusable(false);
        FinalArkanoidIsa.frame2.setSize(1200, 1000);
        FinalArkanoidIsa.frame2.add(new Level4(u));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
        //Frame_levels frame2=new Frame_levels();
        FinalArkanoidIsa.frame2 = new Frame_levels(u);
        FinalArkanoidIsa.frame2.setVisible(true);
        FinalArkanoidIsa.frame2.setFocusable(false);
        FinalArkanoidIsa.frame2.setSize(1200, 1000);
        FinalArkanoidIsa.frame2.add(new Level3(u));

    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
