/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import static MainPackage.FinalArkanoidIsa.frame;
import sun.audio.*; 
/**
 *
 * @author HP
 */
public class start extends javax.swing.JPanel  {

    /**
     * Creates new form start
     */
    public start() {
        initComponents();
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jLabel3.setVisible(false);
        this.setBounds(0, 0, 1196, 1000);
        playSound("ShakeYourBootay.wav");
        
    }
 public void playSound(String filename) {
        try {
            // Open an audio input stream.
            //File sndFile = new File(this.getClass().getResource(filename));
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(this.getClass().getResource(filename));
            // Get a sound clip object.
            Clip clip = AudioSystem.getClip();
            // Play the sound.
            clip.open(audioIn);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 45)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 204, 102));
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setLabel("High Scores");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(320, 480, 320, 50);

        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 45)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 204, 102));
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setLabel("Setting");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(380, 600, 220, 60);

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 45)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 102));
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setLabel("Sound level");
        add(jButton3);
        jButton3.setBounds(320, 550, 330, 40);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 102));
        jLabel2.setText("Enter your name : ");
        add(jLabel2);
        jLabel2.setBounds(340, 510, 306, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setOpaque(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(670, 510, 220, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/right-arrow.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3);
        jLabel3.setBounds(430, 650, 140, 140);

        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 45)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 204, 102));
        jButton7.setText("Start");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(380, 420, 210, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/s22.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -50, 1200, 1100);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String length=jTextField1.getText();
        if(length.length()>0)
        {
            jLabel3.setVisible(true);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jLabel3.setVisible(false);
        System.out.println("here");
      
        FinalArkanoidIsa.frame.hide();
        FinalArkanoidIsa.frame= new JFrame("Bonus++;");
        FinalArkanoidIsa.frame.setSize(1196,1000);
        FinalArkanoidIsa.frame.setLocation(500, 0);
        // FinalArkanoidIsa.frame.add(new start());
        FinalArkanoidIsa.frame.add(new plan(jTextField1.getText()));
        FinalArkanoidIsa. frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        FinalArkanoidIsa.frame.setVisible(true);   
      
   
     

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(evt.getSource()==jButton7)
        {
            jButton7.setVisible(false);
            jButton5.setVisible(false);
            jButton6.setVisible(false);
            jButton3.setVisible(false);
            jLabel2.setVisible(true);
            jTextField1.setVisible(true);
            //jLabel3.setVisible(true);
           // jLabel4.setVisible(false);

        }

    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
